### ISSUE TITLE
Benchmarks seem slow with blaze-builder 0.4.0.1.

### ISSUE THREAD

**Issue by mikehat** [jaspervdj/blaze-markup#21]
Please see the diatribe in my pull request.

Also look at my [blaze-all](https://github.com/mikehat/blaze-all) repo. The branches in there will let you test blaze-markup built against different blaze-builder versions and see the resulting benchmarks.

**Comment by dylex** [comment]
I haven't looked into this but it's quite likely because blaze-builder (as of 0.4) no longer provides real functionality, but is just a wrapper for the standard bytestring builder.  Rewriting blaze-markup to use bytestring builder directly, may recover the performance (though bytestring builder is also somewhat different than blaze-builder was, so it may require other tweaking, too).

**Comment by mikehat** [comment]
I upgraded to ghc 7.8 and platform 2014.2. I can no longer bulid against blaze-builder 0.3.3.4.

The wide discrepancy in bigTable/Utf8 performance is gone, although all the benchmarks run slower now. I'll chock it up to the tradeoffs inherent in progress. I'll focus on the CSS branch, which runs benchmarks only slightly faster than the master branch...
